name: divideai
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.1
  flutter_modular: ^5.0.3
  dartz: ^0.10.1
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  intl: ^0.17.0
  flutter_mobx: ^2.0.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_localizations: 
  #   sdk: flutter         
  mobx_codegen: ^2.0.7+3
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
 

